# SPDX-License-Identifier: Apache-2.0

execute_process(
	COMMAND git describe --long --tags --dirty --always
	WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
	OUTPUT_VARIABLE APP_VERSION
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

string(REPLACE "-" ";" GIT_INFO_LIST ${APP_VERSION})
list(GET GIT_INFO_LIST 0 VERSION_NUMBER)
string(REPLACE "v" "" VERSION_LIST_RAW ${VERSION_NUMBER})
string(REPLACE "." ";" VERSION_LIST ${VERSION_LIST_RAW})
list(GET VERSION_LIST 0 MAJOR_NUMBER)
list(GET VERSION_LIST 1 MINOR_NUMBER)
list(GET GIT_INFO_LIST 1 BUILD_NUMBER)

list(LENGTH VERSION_LIST VERSION_LIST_COUNT)
if (${VERSION_LIST_COUNT} GREATER_EQUAL 3)
	list(GET VERSION_LIST 2 BUILD_NUMBER_ORG)
	MATH(EXPR BUILD_NUMBER "${BUILD_NUMBER_ORG} + ${BUILD_NUMBER}")
endif()

set(VERSION_TAG "v${MAJOR_NUMBER}.${MINOR_NUMBER}.${BUILD_NUMBER}")
set(VERSION ${APP_VERSION})

string(TIMESTAMP BUILD_DATE "\"%Y-%m-%dT%H:%M:%SZ\"" UTC)
